# Generated by Django 3.2.4 on 2021-06-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210614_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergyproduct',
            old_name='allery',
            new_name='allergy',
        ),
    ]
