# Generated by Django 3.2.4 on 2021-06-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
